### ISSUE TITLE
Visual Search through URL often not working

### ISSUE THREAD

**Issue by lklic** [ArtResearch/vision-app#69] opened 2022-02-03 09:46 UTC
The visual search with a URL often does not work.

e.g.
https://upload.wikimedia.org/wikipedia/commons/7/7e/Raphael_-_Madonna_Bridgewater.JPG

returns no results, but if you upload the image it has many results.

Can you please investigate why this is happening and fix?

Thank you

**Comment by sophisid** [comment] 2022-02-07 10:10
The problem occurs in the pastec code. It cannot upload big images. So if we upload this image of mona lisa :
[Mona Lisa Full dimensions](https://upload.wikimedia.org/wikipedia/commons/e/ec/Mona_Lisa%2C_by_Leonardo_da_Vinci%2C_from_C2RMF_retouched.jpg)
it will not return any pastec results because the pastec does not let the image to be uploaded. 
But if we uploade the same image in smaller size :
[Mona Lisa Smaller](https://upload.wikimedia.org/wikipedia/commons/thumb/e/ec/Mona_Lisa%2C_by_Leonardo_da_Vinci%2C_from_C2RMF_retouched.jpg/402px-Mona_Lisa%2C_by_Leonardo_da_Vinci%2C_from_C2RMF_retouched.jpg)
it will upload and return pastec results.
I tried in the front-end to change the url and take a smaller thumbnail of the image but could not apply simple SPARQL rules to the pastec query, to change the url of the image.
Some errors that the console shows are: 
![image](https://user-images.githubusercontent.com/55842445/152767011-9bcc38ca-166c-48c2-a084-1edef6bcdf92.png)
![image](https://user-images.githubusercontent.com/55842445/152766959-d53800af-ff34-4204-b183-491ec55499f2.png)
![image](https://user-images.githubusercontent.com/55842445/152766981-c978d69e-11a2-4b18-8add-52b27c5726bd.png)

**Comment by lklic** [comment] 2022-02-07 15:02
OK but the image that I provided in the issue is 75kb, and it is still not working. I can understand the mona lisa image that is 94MB.

Can you please check this?

**Comment by sophisid** [comment] 2022-02-21 09:39
The issue is now fixed. The problem was that we needed both `https://pharos.artresearch.net/resource/fr/Work_depicted_by_Photo` and `https://artresearch.net/resource/fr/Work_depicted_by_Photo`
As also 
`https://pharos.artresearch.net/resource/vocab/vision/pastec/has_index` and
`https://artresearch.net/resource/vocab/vision/pastec/has_index`

**Closed as completed** 2022-05-10 14:18 UTC
Labels: validation
